// examples/react/src/App.jsx
import React from 'react';
import { BarcodeScannerProvider } from './contexts/BarcodeScannerContext';
import WebSerialBarcodeScannerControl from './components/WebSerialBarcodeScannerControl';
import WebSerialBarcodeScannerResults from './components/WebSerialBarcodeScannerResults';
import { useBarcodeScanner } from './contexts/BarcodeScannerContext';
import './App.css';

const AppContent = () => {
  const { scanner } = useBarcodeScanner();

  // Подсчитываем количество поддерживаемых устройств
  const supportedDevicesCount = scanner ? 
    Object.values(scanner.supportedDevices || {}).reduce((count, vendor) =>
      count + Object.keys(vendor.devices || {}).length, 0) : 0;

  return (
    <div id="app">
      <header className="header-container">
        <div className="title-block">
          <h1>Web Serial Barcode Scanner</h1>
          <p className="caption">Интеграция с Web Serial API для сканеров штрихкодов</p>
        </div>
        <a href="https://github.com/erratir/web-serial-barcode-scanner"
           className="github-link"
           target="_blank"
           rel="noopener noreferrer"
           title="GitHub Repository">
          <svg className="github-icon" viewBox="0 0 24 24">
            <path fill="currentColor" d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
          </svg>
        </a>
      </header>
      
      <main>
        <WebSerialBarcodeScannerControl />
        <WebSerialBarcodeScannerResults />
      </main>

      <footer>
        <p>Это приложение использует Web Serial API для подключения сканеров штрихкодов</p>
        <p>Поддерживаемые устройства: {supportedDevicesCount} моделей</p>
      </footer>
    </div>
  );
};

const App = () => {
  return (
    <BarcodeScannerProvider>
      <AppContent />
    </BarcodeScannerProvider>
  );
};

export default App;

// examples/vue/src/App.vue
<template>
  <div id="app">
    <header class="header-container">
      <div class="title-block">
        <h1>Web Serial Barcode Scanner</h1>
        <p class="caption">Интеграция с Web Serial API для сканеров штрихкодов</p>
      </div>
      <a href="https://github.com/erratir/web-serial-barcode-scanner"
         class="github-link"
         target="_blank"
         title="GitHub Repository">
        <svg class="github-icon" viewBox="0 0 24 24">
          <path fill="currentColor" d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
        </svg>
      </a>
    </header>
    <main>
      <barcode-scanner-control />
      <barcode-scan-results />
    </main>

    <footer>
      <p>Это приложение использует Web Serial API для подключения сканеров штрихкодов</p>
      <p>Поддерживаемые устройства: {{ supportedDevicesCount }} моделей</p>
    </footer>
  </div>
</template>

<script setup>
import {computed, inject} from 'vue';
import BarcodeScannerControl from './components/WebSerialBarcodeScannerControl.vue';
import BarcodeScanResults from './components/WebSerialBarcodeScannerResults.vue';
const scanner = inject('barcodeScanner');

// Подсчитываем количество поддерживаемых устройств
const supportedDevicesCount = computed(() => {
  return Object.values(scanner.supportedDevices).reduce((count, vendor) =>
      count + Object.keys(vendor.devices).length, 0);
});
</script>

<style>
:root {
  --primary-color: #4361ee;
  --secondary-color: #3a0ca3;
  --success-color: #4cc9f0;
  --error-color: #f72585;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  line-height: 1.6;
  color: #333;
  background-color: #f5f7fa;
  min-height: 100vh;
}

header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 16px;
  padding: 10px 0 6px 0;
}

header h1 {
  color: var(--secondary-color);
  margin-bottom: 2px;
  font-size: 22px;
}

.caption {
  color: #666;
  font-size: 0.95em;
}

.title-block { display: flex; flex-direction: column; align-items: flex-start; }

footer {
  text-align: center;
  margin-top: 40px;
  padding: 20px 0;
  color: #666;
  font-size: 0.9em;
  border-top: 1px solid #eee;
}

.github-link {
  display: flex;
  align-items: center;
  color: #333;
  text-decoration: none;
  transition: transform 0.3s;
}

.github-icon {
  width: 36px;
  height: 36px;
}

.github-link:hover {
  transform: scale(1.1);
}
</style>
