// examples/react/src/components/WebSerialBarcodeScannerResults.jsx
import React from 'react';
import { useBarcodeScannerStore } from '../stores/barcodeScannerStore';

const WebSerialBarcodeScannerResults = () => {
  const { rawData, parsedData } = useBarcodeScannerStore();

  // Форматируем данные для отображения (новые сверху)
  const formattedRawData = [...rawData].reverse();
  const formattedParsedData = [...parsedData].reverse();

  // Форматируем дату
  const formatDate = (timestamp) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString() + '.' +
        date.getMilliseconds().toString().padStart(3, '0');
  };

  // Форматируем parsed данные для отображения
  const formatParsedData = (data) => {
    if (!data) return '';
    return JSON.stringify(data, null, 2);
  };

  return (
    <div className="scan-results">
      <h2>Результаты сканирования</h2>

      <div className="data-columns">
        <div className="column">
          <h3>Отсканированные данные:</h3>
          <div className="data-container">
            {formattedRawData.length === 0 ? (
              <div className="empty-message">
                Данные от сканера будут отображаться здесь
              </div>
            ) : (
              <div className="data-list">
                {formattedRawData.map((item, index) => (
                  <div key={index} className="data-item">
                    <div className="timestamp">{formatDate(item.timestamp)}</div>
                    <div className="data-value">{item.data}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="column">
          <h3>Обработанные данные:</h3>
          <div className="data-container">
            {formattedParsedData.length === 0 ? (
              <div className="empty-message">
                Обработанные данные будут отображаться здесь
              </div>
            ) : (
              <div className="data-list">
                {formattedParsedData.map((item, index) => (
                  <div key={index} className="data-item parsed">
                    <div className="timestamp">{formatDate(item.timestamp)}</div>

                    {item.error ? (
                      <div className="error">
                        <strong>Ошибка:</strong> {item.error}
                        <div className="raw-data">Исходные данные: {item.raw}</div>
                      </div>
                    ) : (
                      <>
                        {item.type && <div className="data-type">Тип: {item.type}</div>}
                        <pre className="parsed-json">{formatParsedData(item.data)}</pre>
                      </>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default WebSerialBarcodeScannerResults;

// examples/vue/src/components/WebSerialBarcodeScannerResults.vue
<template>
  <div class="scan-results">
    <h2>Результаты сканирования</h2>

    <div class="data-columns">
      <div class="column">
        <h3>Отсканированные данные:</h3>
        <div class="data-container">
          <div v-if="rawData.length === 0" class="empty-message">
            Данные от сканера будут отображаться здесь
          </div>
          <div v-else class="data-list">
            <div v-for="(item, index) in formattedRawData" :key="index" class="data-item">
              <div class="timestamp">{{ formatDate(item.timestamp) }}</div>
              <div class="data-value">{{ item.data }}</div>
            </div>
          </div>
        </div>
      </div>

      <div class="column">
        <h3>Обработанные данные:</h3>
        <div class="data-container">
          <div v-if="parsedData.length === 0" class="empty-message">
            Обработанные данные будут отображаться здесь
          </div>
          <div v-else class="data-list">
            <div v-for="(item, index) in formattedParsedData" :key="index" class="data-item parsed">
              <div class="timestamp">{{ formatDate(item.timestamp) }}</div>

              <div v-if="item.error" class="error">
                <strong>Ошибка:</strong> {{ item.error }}
                <div class="raw-data">Исходные данные: {{ item.raw }}</div>
              </div>

              <div v-else>
                <div v-if="item.type" class="data-type">Тип: {{ item.type }}</div>
                <pre class="parsed-json">{{ formatParsedData(item.data) }}</pre>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { storeToRefs } from 'pinia';
import { useBarcodeScannerStore } from '../stores/web-serial-barcode-scanner.js'

const store = useBarcodeScannerStore();
const { rawData, parsedData } = storeToRefs(store);

// Форматируем данные для отображения
const formattedRawData = computed(() => {
  return [...rawData.value].reverse();
});

const formattedParsedData = computed(() => {
  return [...parsedData.value].reverse();
});

// Форматируем дату
const formatDate = (timestamp) => {
  const date = new Date(timestamp);
  return date.toLocaleTimeString() + '.' +
      date.getMilliseconds().toString().padStart(3, '0');
};

// Форматируем parsed данные для отображения
const formatParsedData = (data) => {
  if (!data) return '';
  return JSON.stringify(data, null, 2);
};
</script>

<style scoped>
.scan-results {
  max-width: 100%;
  margin: 20px auto;
  padding: 0 20px;
}

.data-columns {
  display: flex;
  gap: 20px;
  margin-top: 10px;
}

.column {
  flex: 1;
  min-width: 280px;
}

.column h3 {
  margin: 0 0 10px 0;
  font-size: 1.2em;
  color: #444;
}

.data-container {
  border: 1px solid #ccc;
  border-radius: 4px;
  height: 400px;
  overflow-y: auto;
  background-color: #f9f9f9;
}

.empty-message {
  padding: 20px;
  text-align: center;
  color: #666;
  font-style: italic;
}

.data-list {
  padding: 10px;
}

.data-item {
  padding: 12px;
  margin-bottom: 8px;
  background-color: white;
  border-radius: 4px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

.timestamp {
  font-size: 12px;
  color: #666;
  margin-bottom: 5px;
}

.data-value {
  word-break: break-all;
  font-family: monospace;
  font-size: 14px;
}

.parsed .data-type {
  font-weight: bold;
  color: #4361ee;
  margin-bottom: 5px;
}

.parsed-json {
  margin: 0;
  padding: 8px;
  background-color: #f0f0f0;
  border-radius: 4px;
  font-family: monospace;
  font-size: 13px;
  white-space: pre-wrap;
  word-wrap: break-word;
  border: 1px solid #ddd;
}

.error {
  color: #dc3545;
}

.raw-data {
  margin-top: 5px;
  font-size: 12px;
  color: #666;
  font-family: monospace;
}
</style>
