// examples/vue/src/components/CustomDeviceModal.vue
<template>
  <div class="modal-backdrop" @click.self="emitClose">
    <div class="modal">
      <h3>Добавить пользовательское устройство</h3>

      <div class="form">
        <div class="field">
          <label for="vid">VID (4 символа)</label>
          <input id="vid" v-model="vid" maxlength="4" :class="{ error: vidError }" placeholder="Например, 1A86" />
          <div v-if="vidError" class="error-text">{{ vidError }}</div>
        </div>

        <div class="field">
          <label for="pid">PID (4 символа)</label>
          <input id="pid" v-model="pid" maxlength="4" :class="{ error: pidError }" placeholder="Например, 5723" />
          <div v-if="pidError" class="error-text">{{ pidError }}</div>
        </div>
      </div>

      <div class="actions">
        <button class="btn primary" @click="onSubmit">Добавить</button>
        <button class="btn" @click="emitClose">Отмена</button>
      </div>
    </div>
  </div>
  
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue';

const emit = defineEmits(['submit', 'close']);

const vid = ref('');
const pid = ref('');
const vidError = ref('');
const pidError = ref('');

const validate = () => {
  vidError.value = '';
  pidError.value = '';
  let ok = true;
  if (!/^[0-9A-F]{4}$/i.test(vid.value)) {
    vidError.value = 'VID должен содержать 4 шестнадцатеричных символа';
    ok = false;
  }
  if (!/^[0-9A-F]{4}$/i.test(pid.value)) {
    pidError.value = 'PID должен содержать 4 шестнадцатеричных символа';
    ok = false;
  }
  return ok;
};

const onSubmit = () => {
  if (!validate()) return;
  emit('submit', { vid: vid.value.toUpperCase(), pid: pid.value.toUpperCase() });
};

const emitClose = () => emit('close');

const onKeydown = (e) => {
  if (e.key === 'Escape') emitClose();
};

onMounted(() => {
  window.addEventListener('keydown', onKeydown);
});

onUnmounted(() => {
  window.removeEventListener('keydown', onKeydown);
});
</script>

<style scoped>
.modal-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.35);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal {
  width: min(520px, 92vw);
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);
  padding: 16px;
  border: 1px solid #e6e6e6;
}

.modal h3 {
  margin: 0 0 10px 0;
  font-size: 18px;
  color: #333;
}

.form {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}

.field { display: flex; flex-direction: column; }
.field label { font-size: 13px; color: #444; margin-bottom: 4px; }
.field input { padding: 8px 10px; border: 1px solid #ddd; border-radius: 6px; font-size: 14px; }
.field input.error { border-color: #dc3545; }
.error-text { color: #dc3545; font-size: 12px; margin-top: 4px; }

.actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 14px;
}

.btn { padding: 8px 12px; border: 1px solid #ddd; background: #fff; border-radius: 6px; cursor: pointer; }
.btn.primary { background: #4361ee; color: #fff; border-color: #4361ee; }
.btn.primary:hover { background: #3a56d4; border-color: #3a56d4; }
.btn:hover { background: #f5f5f5; }

@media (max-width: 560px) { .form { grid-template-columns: 1fr; } }
</style>

// examples/react/src/components/CustomDeviceModal.jsx
import React, { useState, useEffect } from 'react';
import { useBarcodeScanner } from '../contexts/BarcodeScannerContext';

const CustomDeviceModal = ({ isOpen, onClose }) => {
  const { scanner } = useBarcodeScanner();
  
  const [vid, setVid] = useState('');
  const [pid, setPid] = useState('');
  const [vidError, setVidError] = useState('');
  const [pidError, setPidError] = useState('');

  // useEffect должен вызываться всегда, независимо от условий
  useEffect(() => {
    const onKeydown = (e) => {
      if (e.key === 'Escape') handleClose();
    };

    if (isOpen) {
      window.addEventListener('keydown', onKeydown);
      return () => window.removeEventListener('keydown', onKeydown);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const validate = () => {
    setVidError('');
    setPidError('');
    let ok = true;
    
    if (!/^[0-9A-F]{4}$/i.test(vid)) {
      setVidError('VID должен содержать 4 шестнадцатеричных символа');
      ok = false;
    }
    
    if (!/^[0-9A-F]{4}$/i.test(pid)) {
      setPidError('PID должен содержать 4 шестнадцатеричных символа');
      ok = false;
    }
    
    return ok;
  };

  const handleSubmit = () => {
    if (!validate()) return;
    
    const success = scanner.addDevice(vid.toUpperCase(), pid.toUpperCase());
    if (success) {
      setVid('');
      setPid('');
      setVidError('');
      setPidError('');
      onClose();
    }
  };

  const handleClose = () => {
    setVid('');
    setPid('');
    setVidError('');
    setPidError('');
    onClose();
  };

  return (
    <div className="modal-backdrop" onClick={handleClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h3>Добавить пользовательское устройство</h3>

        <div className="form">
          <div className="field">
            <label htmlFor="vid">VID (4 символа)</label>
            <input 
              id="vid" 
              value={vid} 
              onChange={(e) => setVid(e.target.value)}
              maxLength={4} 
              className={vidError ? 'error' : ''} 
              placeholder="Например, 1A86" 
            />
            {vidError && <div className="error-text">{vidError}</div>}
          </div>

          <div className="field">
            <label htmlFor="pid">PID (4 символа)</label>
            <input 
              id="pid" 
              value={pid} 
              onChange={(e) => setPid(e.target.value)}
              maxLength={4} 
              className={pidError ? 'error' : ''} 
              placeholder="Например, 5723" 
            />
            {pidError && <div className="error-text">{pidError}</div>}
          </div>
        </div>

        <div className="actions">
          <button className="btn primary" onClick={handleSubmit}>
            Добавить
          </button>
          <button className="btn" onClick={handleClose}>
            Отмена
          </button>
        </div>
      </div>
    </div>
  );
};

export default CustomDeviceModal;
